### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by ajeema** [discordianfish/pager-hours#11]
Please provide build instructions. Also the packages it is looking for do not seem to exist? Can you provide paths to the dependant packages?

**Comment by discordianfish** [comment]
This project is pretty much abandoned but I fixed the imports and added a line about installing it. Feel free to re-open if is still not buildable. I any of the involved APIs have changed, feel free to submit a PR to fix that but I won't get to that since I haven't been using this thing for years.

**Comment by ajeema** [comment]
I can download packages now but even though the credentials are correct I get the following:
2022/11/16 12:32:50 Couldn't get hours for policy Couldn't get schedule entries for : Couldn't request schedule/: Status %!s(int=400) != 200:

am I missing something on my end?

**Comment by discordianfish** [comment]
They probably changed the API :-/ Looks like schedule.Id is empty here: https://github.com/discordianfish/pager-hours/blob/a8e72b82fc91357aa621804987f034caa87dfa75/pager-hours.go#L131
